site_name: ویکی داریا باند
site_url: https://ramabondanp.github.io/daria-bond-wiki/
theme:
  name: material
  palette:
    scheme: slate
    primary: black
  language: fa
  icon:
    repo: fontawesome/brands/github
  features:
    - search.highlight
    - navigation.sections

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  custom_dir: overrides

plugins:
  - search
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      languages:
        - locale: fa
          name: فارسی
          build: true
          default: true
          site_name: ویکی داریا باند
        - locale: en
          name: English
          build: true
          site_name: Daria Bond Wiki
          nav_translations:
            "خانه": "Home"
            "آنلاک بوتلودر": "Unlock Bootloader"
            "کاستوم رام": "Custom ROMs"
            "لیست کاستوم رام ها": "Custom ROM List"
            "بارگیری رام رسمی": "Official ROM Download"
            "خطا های رایج": "Common Errors"
      material: true

extra:
  alternate:
    - name: فارسی
      link: /daria-bond-wiki/
      lang: fa
    - name: English
      link: /daria-bond-wiki/en/
      lang: en

extra_css:
  - stylesheets/custom.css

# extra_javascript:
#   - javascripts/custom.js

repo_url: https://github.com/nimafanniasl/daria-bond-wiki/
repo_name: GitHub
edit_uri: edit/main/docs/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
 - خانه: index.md
 - آنلاک بوتلودر: unlock-bootloader.md
 - کاستوم رام:
    - لیست کاستوم رام ها: custom-roms/custom-rom-list.md
 - بارگیری رام رسمی: official-rom.md
 - خطا های رایج: common-errors.md